name: 'Bash shell beautifier'
description: 'A GitHub Action for beautysh'
author: 'illvart'

branding:
  icon: 'code'
  color: 'green'

inputs:
  args:
    description: 'Arguments provided to beautysh'
    required: false
    default: '*.sh'
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}
